[package]
name = "hash-functions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc"]}
hex = "0.4.3"
sha2 = "0.10.8"
sha3 = "0.10.8"
