[package]
name = "password-hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Simplifiles the error handling
anyhow = "1.0.80"
argon2 = { version ="0.5.3" }
dotenv = "0.15.0"